version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.6
jobs:
  test:
    docker:
      - image: cimg/php:8.1.2-browsers
        environment:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: gas_sikat_testing
          DB_USERNAME: root
          DB_PASSWORD: ""
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Install Node
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install -y nodejs
      # Composer cache
      - restore_cache:
          keys:
          - composer-v1-{{ checksum "composer.lock" }}
          - composer-v1-
      - run: composer update -n --prefer-dist --ignore-platform-reqs
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      # Node cache
      - restore_cache:
          keys:
            - node-v4-{{ checksum "package.json" }}
            - node-v4-
      - run: npm install
      - save_cache:
          key: node-v4-{{ checksum "package.json" }}
          paths:
            - node-modules
            - ~/.yarn
      - run:
          name: Setup Environment
          command: |
            cp .env.testing .env
            cp .env.testing .env.dusk.local
            php artisan key:generate
            mysql -h $DB_HOST -u $DB_USERNAME -e "CREATE DATABASE $DB_DATABASE"
      - run:
          name: Run Http Tests
          command: ./vendor/bin/phpunit tests/Feature
      - run:
          name: Start Chrome Driver
          command: ./vendor/laravel/dusk/bin/chromedriver-linux
          background: true
      - run:
          name: Run Laravel Server
          command: php artisan serve
          background: true
      - run:
          name: Run Browser Tests
          command: php artisan dusk
workflows:
  version: 2
  workflows:
    jobs:
      - test