version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.17.0
      - image: cimg/php:8.1.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Composer Dependencies
          command: composer install --no-interaction --prefer-dist
      - run:
          name: Run Tests
          command: php artisan test
      - run:
          name: Build Assets
          command: npm run build
workflows:
  version: 2
  build:
    jobs:
      - build